      require 'rubygems'
      require 'betabuilder'
      BetaBuilder::Tasks.new do |config|
        config.target = 'Authorly'
        config.configuration = 'Adhoc'
        config.app_name = 'Authorly'

        config.deploy_using(:web) do |web|
          web.deploy_to = 'https://authorly-staging.s3.amazonaws.com/compiled_applications/2'
          web.remote_host = 'fake_path'
          web.remote_directory = 'fake_directory'
        end
      end
